"""Server brain: Postgres full-text search — one brain for every harness, office agent and dashboard.

psycopg is imported here only, so a clone on the SQLite default never needs it installed.
"""

from threading import Lock

import psycopg
from psycopg.rows import dict_row

from services.brain.base import ID_BASE, BrainBackend, search_terms

_COLUMNS = "id, category, content, author, to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') AS created_at"  # = SQLite's format

# 'simple' text config: no stemming or stopwords — the notes mix English, Indonesian and Japanese.
_SCHEMA = f"""
CREATE TABLE IF NOT EXISTS facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH {ID_BASE + 1}) PRIMARY KEY,
    category TEXT NOT NULL,
    content TEXT NOT NULL,
    author TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED
);
CREATE INDEX IF NOT EXISTS facts_tsv_idx ON facts USING GIN (tsv);
CREATE TABLE IF NOT EXISTS journal (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    content TEXT NOT NULL,
    author TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS journal_kind_idx ON journal (kind, created_at);
"""


class PostgresBrain(BrainBackend):
    def __init__(self, dsn: str):
        if not dsn:
            raise ValueError("BRAIN_BACKEND=postgres needs BRAIN_DSN")
        self._dsn = dsn
        self._lock = Lock()
        self._conn: psycopg.Connection | None = None
        self._run(lambda cur: cur.execute(_SCHEMA))

    def _run(self, fn):
        """One statement on the persistent connection; reconnect once if it went stale."""
        with self._lock:
            for attempt in (1, 2):
                try:
                    if self._conn is None or self._conn.closed:
                        self._conn = psycopg.connect(self._dsn, autocommit=True, connect_timeout=5,
                                                     row_factory=dict_row)
                    with self._conn.cursor() as cur:
                        return fn(cur)
                except psycopg.OperationalError:
                    self._conn = None
                    if attempt == 2:
                        raise

    def _insert(self, category, content, author):
        return self._run(lambda cur: cur.execute(
            "INSERT INTO facts (category, content, author) VALUES (%s, %s, %s) RETURNING id",
            (category, content, author)).fetchone()["id"])

    def all(self, category=None):
        where, args = ("WHERE category = %s", (category,)) if category else ("", ())
        return self._run(lambda cur: cur.execute(
            f"SELECT {_COLUMNS} FROM facts {where} ORDER BY created_at, id", args).fetchall())

    def search(self, query, limit=20):
        terms = search_terms(query)
        if not terms:
            return []
        tsquery = " | ".join(terms)  # terms are [a-z0-9]+ only, so safe inside to_tsquery
        return self._run(lambda cur: cur.execute(
            f"SELECT {_COLUMNS} FROM facts, to_tsquery('simple', %s) q WHERE tsv @@ q "
            "ORDER BY ts_rank(tsv, q) DESC LIMIT %s", (tsquery, limit)).fetchall())

    def update(self, fact_id, content):
        return self._run(lambda cur: cur.execute(
            "UPDATE facts SET content = %s, updated_at = now() WHERE id = %s",
            (content, fact_id)).rowcount > 0)

    def delete(self, fact_id):
        return self._run(lambda cur: cur.execute(
            "DELETE FROM facts WHERE id = %s", (fact_id,)).rowcount > 0)

    def count(self):
        return self._run(lambda cur: cur.execute("SELECT COUNT(*) AS n FROM facts").fetchone()["n"])

    def log(self, kind, content, author):
        def run(cur):
            cur.execute("INSERT INTO journal (kind, content, author) VALUES (%s, %s, %s)", (kind, content, author))
            cur.execute("DELETE FROM journal WHERE kind = %s AND created_at < now() - make_interval(days => %s)",
                        (kind, self.JOURNAL_KEEP_DAYS))
        self._run(run)

    def recent(self, kind, hours, limit=10):
        return self._run(lambda cur: cur.execute(
            "SELECT content, author, (EXTRACT(EPOCH FROM now() - created_at) / 60)::int AS age_minutes "
            "FROM journal WHERE kind = %s AND created_at >= now() - make_interval(mins => %s) "
            "ORDER BY created_at DESC, id DESC LIMIT %s", (kind, int(hours * 60), limit)).fetchall())
